select
    game_id,
    SAFE_CAST(game_start_utc AS TIMESTAMP)          as game_start_at,
    game_duration,
    game_mode,
    game_type,
    game_version,
    -- BigQuery: SPLIT returns an array, use index [OFFSET()]
    CONCAT(
        SPLIT(game_version, '.')[OFFSET(0)], '.',
        SPLIT(game_version, '.')[OFFSET(1)]
    )                                               as patch,
    map_id,
    platform_id,
    queue_id,
    participant_id,
    puuid,
    NULLIF(summoner_name, '')                       as summoner_name,
    summoner_id,
    summoner_level,
    champion_id,
    champion_name,
    team_id,
    SAFE_CAST(win AS BOOL)                          as is_winner,
    NULLIF(team_position, '')                       as position,
    lane,
    role,
    kills, deaths, assists,
    baron_kills, dragon_kills,
    total_damage_dealt_to_champions,
    physical_damage_dealt_to_champions,
    magic_damage_dealt_to_champions,
    true_damage_dealt_to_champions,
    damage_dealt_to_objectives,
    damage_dealt_to_turrets,
    total_damage_taken,
    gold_earned, gold_spent,
    time_ccing_others,
    vision_score,
    wards_placed, wards_killed,
    vision_wards_bought_in_game,
    item0, item1, item2, item3, item4, item5,
    item6                                           as trinket_item,
    solo_tier, solo_rank, solo_lp,
    solo_wins, solo_losses,
    flex_tier, flex_rank, flex_lp,
    flex_wins, flex_losses,
    champion_mastery_level,
    champion_mastery_points,
    SAFE_CAST(champion_mastery_lastPlayTime_utc AS TIMESTAMP) as mastery_last_played_at,
    final_health, final_healthMax,
    final_armor, final_magicResist,
    final_attackDamage, final_abilityPower,
    final_attackSpeed, final_movementSpeed,
    final_abilityHaste

from {{ source('league_data_raw', 'matches') }}