sources:
  - name: "{{ var('dataset_id') }}"
    database: "{{ var('project_id') }}" #GCP project ID
    schema: "{{ var('dataset_id') }}" # Or name of your BigQuery dataset
    
    tables:
      - name: matches
